framework:
  translator: ~

  # app/config/config.yml
  fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Personne
    from_email:
      address: "%mailer_user%"
      sender_name: "%mailer_user%"

  #Swiftailer config

  swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password : "%mailer_password%"
    spool : {type : memory}